services:
  mongo:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "mongo_data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - certbot_data:/var/www/certbot/:ro
      - certificates:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_data:/var/www/certbot/:rw
      - certificates:/etc/letsencrypt/:rw

volumes:
  mongo_data:
  certbot_data:
  certificates:

networks:
  default:
    name: mystery
